// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hkgjuxefcgcahipvwjeb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhrZ2p1eGVmY2djYWhpcHZ3amViIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMzMTg1MzEsImV4cCI6MjA2ODg5NDUzMX0.-Crh_kuTZ3lbgyMleqJ7vhC9bKUaDVA36qK3Wf3Cn6E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});